### ISSUE TITLE
Does not work if there are no intrones in sequences

### ISSUE THREAD

**Issue by IrynaYa** [Mycology-Microbiology-Center/IntronTrimmer#1]
If no charset intron is given, a mistake appears

Error in strsplit(x = introns, split = " ")[[1]] : 
  subscript out of bounds

**Comment by vmikk** [comment]
Fixed via [7102c63](https://github.com/Mycology-Microbiology-Center/nex2tbl/commit/7102c636ceee6033dafb665f2feb1eafbbee0f33)

**Comment by IrynaYa** [comment]
tested on my data, it works
